### ISSUE TITLE
Linnaeus University

### ISSUE THREAD

**Issue by akerren** [mcnuttandrew/vis-phd-positions#10]
Professor: Andreas Kerren
Personal Page: https://www.itn.liu.se/~andke01/
University: Linnaeus University
University Website: https://lnu.se/en
Lab Website: https://cs.lnu.se/isovis/
Contact Info: andreas.kerren@lnu.se
Topics: Information visualization, visual analytics, network visualization, human-computer interaction, dimensionality reduction, ML4VIS, VIS4ML, explainable AI/ML, text visualization
Looking for: PostDocs
Timeline: anytime

**Comment by mcnuttandrew** [comment]
Added!
