### ISSUE TITLE
PhD student position in computer science with focus on game technology/game analytics

### ISSUE THREAD

**Issue by eelir** [mcnuttandrew/vis-phd-positions#11]
Professor: Veronica Sundstedt
Personal Page: 
University: Blekinge Institute of Technology
University Website: https://www.bth.se
Lab Website: 
Contact Info: veronica.sundstedt@bth.se
Topics: Visual Analytics, Game Analytics
Looking for: PhD, apply [here](https://tinyurl.com/vavmut2u).
Timeline: Application deadline 2023-10-31

**Comment by mcnuttandrew** [comment]
Added!
