### ISSUE TITLE
UC Davis

### ISSUE THREAD

**Issue by dyuliu** [mcnuttandrew/vis-phd-positions#12]
Professor: Dongyu Liu
Personal Page: https://dongyu.tech/
University: UC Davis
University Website: https://cs.ucdavis.edu/directory/dongyu-liu
Lab Website: under construction~
Contact Info: dyuliu@ucdavis.edu
Topics: Visual Analytics, Human-Centered AI 
Looking for: PhD
Timeline: Fall 24

**Comment by mcnuttandrew** [comment]
Added! Feel free to file another issue once you've created your lab website!

**Comment by dyuliu** [comment]
Thank you!
