### ISSUE TITLE
PhD in Visualisation

### ISSUE THREAD

**Issue by maya70** [mcnuttandrew/vis-phd-positions#13]
Professor: Mai Elshehaly & Jo Wood
Personal Page: http://invisai.com/mai/
University: giCentre - City, University of London 
University Website: www.city.ac.uk
Lab Website: giCentre.net
Contact Info: mai.elshehaly@city.ac.uk
Topics: Visualisation, population health, visual analytics 
Looking for: PhD candidates for two fully funded scholarships 
Timeline: Spring / Fall 24

**Comment by mcnuttandrew** [comment]
Added!
