### ISSUE TITLE
Arizona State University

### ISSUE THREAD

**Issue by chrisbryan** [mcnuttandrew/vis-phd-positions#14]
Professor: Chris Bryan
Personal Page: https://chrisbryan.github.io/
University: Arizona State Univeresity
University Website: https://scai.engineering.asu.edu/
Contact Info: cbryan16@asu.edu
Topics: Visualization for XAI, Visualization for Education, Cybersecurity/Privacy-related Visualization
Looking for: PhD
Timeline: Fall 24

**Comment by mcnuttandrew** [comment]
Added!
