### ISSUE TITLE
New PhD position Linköping University

### ISSUE THREAD

**Issue by alexanderbock** [mcnuttandrew/vis-phd-positions#15]
Professor: Alexander Bock
Personal Page: https://immvis.github.io/personnel/alebo68/
University: Linköping University
University Website: https://liu.se/en/research/media-and-information-technology-mit
Lab Website: https://immvis.github.io
Contact Info: alexander.bock@liu.se
Topics: Real-time large-scale temporary volumetric rendering structures and their applications. Think Quadtree but in 4D.
Looking for: PhD
Timeline: asap

**Comment by mcnuttandrew** [comment]
Added!
