### ISSUE TITLE
Add Dom

### ISSUE THREAD

**Issue by domoritz** [mcnuttandrew/vis-phd-positions#2]
Professor: Dominik Moritz
Personal Page: https://www.domoritz.de
University: Carnegie Mellon University
University Website: https://hcii.cmu.edu
Lab Website: https://dig.cmu.edu
Contact Info: domoritz@cmu.edu
Topics: Tools, Scalability, Accessibility, Machine Learning

**Comment by mcnuttandrew** [comment]
Done!
