### ISSUE TITLE
New listing for Northwestern University

### ISSUE THREAD

**Issue by jhullman** [mcnuttandrew/vis-phd-positions#4]
Professor: Jessica Hullman
Personal Page: http://users.eecs.northwestern.edu/~jhullman/
University: Northwestern University
University Website: https://www.mccormick.northwestern.edu/research-faculty/directory/profiles/hullman-jessica.html
Lab Website: https://mucollective.northwestern.edu/
Contact Info: jessica.hullman@gmail.com
Topics: Visualization + statistical decision theory, information economics
Looking for: PhD
Timeline: Fall 24

**Comment by mcnuttandrew** [comment]
Added! I'll refresh the page in a bit!
