### ISSUE TITLE
Personalising visualization

### ISSUE THREAD

**Issue by binocularity** [mcnuttandrew/vis-phd-positions#5]
Professor: Nicolas S. Holliman
Personal Page: https://www.kcl.ac.uk/people/nicolas-s.-holliman
University: King's College London
University Website: https://www.kcl.ac.uk/
Lab Website: https://www.kcl.ac.uk/research/hcc
Contact Info: https://www.jobs.ac.uk/job/DCM683/phd-studentship-personalising-adjustments-to-information-visualisations-for-optimal-perception-accounting-for-individual-differences-including-ageing
Topics: Personalising visualization 
Looking for: PhD
Timeline: January 24

**Comment by mcnuttandrew** [comment]
Added! I'll update the website soon
