### ISSUE TITLE
New listing for Purdue

### ISSUE THREAD

**Issue by pparsons** [mcnuttandrew/vis-phd-positions#6]
Professor: Paul Parsons
Personal Page: www.paulcparsons.com
University: Purdue University
University Website: www.purdue.edu
Lab Website: www.dvclab.net
Contact Info: parsonsp@purdue.edu
Topics: vis design practice; vis design cognition; vis in complex socio-technical systems
Looking for: PhD
Timeline: Spring 24; Fall 24

**Comment by mcnuttandrew** [comment]
Added! Update should come through shortly
