### ISSUE TITLE
Utah State University

### ISSUE THREAD

**Issue by choissac** [mcnuttandrew/vis-phd-positions#7]
Professor: Isaac Cho
Personal Page: https://vizus.cs.usu.edu/isaac.cho
University: Utah State University
University Website: https://www.usu.edu/
Lab Website: https://vizus.cs.usu.edu
Contact Info: isaac.cho@usu.edu
Topics: big data analytics, immersive analytics, human factors in VR/AR/3DUI
Looking for: PhD
Timeline: Fall 24

**Comment by mcnuttandrew** [comment]
Added! Website will be updated shortly
