### ISSUE TITLE
Open PhD Position in Netherlands

### ISSUE THREAD

**Issue by angeloschatzimparmpas** [mcnuttandrew/vis-phd-positions#8]
Professor: Angelos Chatzimparmpas
Personal Page: https://www.angeloschatzimparmpas.com/
University: Utrecht University
University Website: https://www.uu.nl/en
Lab Website: https://vig.science.uu.nl/
Contact Info: angelos.chatzimparmpas@gmail.com
Topics: Visualization Tools/Systems, ML Interpretability, Explainable AI, Model Checking, Uncertainty Quantification in ML
Looking for: PhD
Timeline: Spring/Fall 24

**Comment by mcnuttandrew** [comment]
Added! Website should deploy shortly
