### ISSUE TITLE
Purdue University

### ISSUE THREAD

**Issue by angusforbes** [mcnuttandrew/vis-phd-positions#9]
Professor: Angus Forbes
Personal Page: https://polytechnic.purdue.edu/profile/agforbes
University: Purdue University
University Website: https://polytechnic.purdue.edu/visualization-research-group
Lab Website: https://angusforbes.com
Contact Info: agforbes@purdue.edu
Topics: Visualization of scientific data, real-time graphics, neural graphics, generative ML, computational art, creative AI, natural language interfaces for science databases
Looking for: PhD students, Postdoctoral researchers
Timeline: Fall 24

**Comment by mcnuttandrew** [comment]
Added! Website will update shortly

**Comment by angusforbes** [comment]
Thanks!! -Angus
